name: appgo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.14+1
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^ 1.0.1
  property_change_notifier: ^0.2.0
  rxdart: ^0.22.6
  mobx: 0.3.9
  http: ^0.12.0
  connectivity: ^0.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  page_indicator: ^0.3.0
  flappy_search_bar: 1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/images_for_Login/logo@2x.png
    - assets/images/images_for_Login/icono_held.png
    - assets/images/images_for_Login/icono_filtrar@3x.png
    - assets/images/images_for_Login/key@3x.png
    - assets/images/images_for_Login/images_indicador/indicador_activo@3x.png
    - assets/images/images_for_Login/images_indicador/indicador_inactivo@3x.png
    - assets/images/images_for_dashboard/recibidas_blue.png
    - assets/images/images_for_dashboard/recibidas_white.png
    - assets/images/images_for_dashboard/activas.png
    - assets/images/images_for_dashboard/activas_blue.png
    - assets/images/images_for_dashboard/aprobadas_blue.png
    - assets/images/images_for_dashboard/aprobadas.png
    - assets/images/images_for_dashboard/calificadas_blue.png
    - assets/images/images_for_dashboard/calificadas.png
    - assets/images/images_for_dashboard/compradas_blue.png
    - assets/images/images_for_dashboard/compradas.png
    - assets/images/images_for_dashboard/icono_filtrar@3x.png
    - assets/images/images_for_dashboard/held_blue.png
    - assets/images/images_for_dashboard/held.png
    - assets/images/images_for_dashboard/document@3x.png
    - assets/images/images_for_dashboard/separator@3x.png
    - assets/images/images_for_dashboard/pendientes_blue.png
    - assets/images/images_for_dashboard/pendientes.png
    - assets/images/images_for_dashboard/rechazadas_blue.png
    - assets/images/images_for_dashboard/rechazadas.png
    - assets/images/images_for_dashboard/warning@3x.png
    - assets/images/images_for_DrawerLeft/boletines.png
    - assets/images/images_for_DrawerLeft/conversion.png
    - assets/images/images_for_DrawerLeft/dashboard.png
    - assets/images/images_for_DrawerLeft/noticias.png
    - assets/images/images_for_DrawerLeft/preguntas.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DINAlternate-Bold.ttf
        - asset: assets/fonts/DINPro-Bold.otf
        - asset: assets/fonts/DINPro-CondensedBold.otf
        - asset: assets/fonts/DINPro-Medium.otf
        - asset: assets/fonts/Louis-BoldItalic.ttf
        - asset: assets/fonts/Louis-CondensedDemi.ttf
        - asset: assets/fonts/Louis-CondensedRegular.ttf
          style: normal
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
